// English strings. Content keys follow `<family>.<id>.name|desc`.
// The validator (tests/content.test.ts) fails if any content item lacks its keys.

export const EN: Record<string, string> = {
  "game.title": "Lemon Lane",
  "game.subtitle": "Sunny Stand",
  "game.tagline": "Plant a little. Sell a little. Grow a lot.",

  // Upgrades
  "upgrade.lemon_tree.name": "Lemon Tree",
  "upgrade.lemon_tree.desc": "Lemons ripen faster, and the tree grows extra fruit every few levels.",
  "upgrade.signboard.name": "Signboard",
  "upgrade.signboard.desc": "A bigger, brighter sign brings neighbors by more often.",
  "upgrade.juice_press.name": "Juice Press",
  "upgrade.juice_press.desc": "Squeezes drinks faster, and every drink sells for a bit more.",
  "upgrade.basket.name": "Basket",
  "upgrade.basket.desc": "Holds more lemons between the tree and the press.",
  "upgrade.stand_counter.name": "Stand Counter",
  "upgrade.stand_counter.desc": "More room for ready drinks and a longer, happier queue.",
  "upgrade.flower_pots.name": "Flower Pots",
  "upgrade.flower_pots.desc": "Pretty pots make customers a little more patient and a little more generous.",
  "upgrade.ice_box.name": "Ice Box",
  "upgrade.ice_box.desc": "Frosty drinks for fancy orders: premium orders appear more often and pay more.",
  "upgrade.sun_umbrella.name": "Sun Umbrella",
  "upgrade.sun_umbrella.desc": "Shade for the queue. Customers happily wait longer.",
  "upgrade.cash_register.name": "Cash Register",
  "upgrade.cash_register.desc": "Quicker checkout keeps combos alive longer and invites tips.",
  "upgrade.recipe_book.name": "Recipe Book",
  "upgrade.recipe_book.desc": "Cheaper recipe discoveries, and favorite drinks delight customers more.",
  "upgrade.helper_bench.name": "Helper Bench",
  "upgrade.helper_bench.desc": "A seat for one more helper, and everyone works a little quicker.",
  "upgrade.delivery_cart.name": "Delivery Cart",
  "upgrade.delivery_cart.desc": "Rolls spare drinks around the block, and keeps earning while you're away.",

  // Recipes
  "recipe.classic.name": "Classic Lemonade",
  "recipe.classic.desc": "Lemon and water. A reliable starter drink.",
  "recipe.honey_lemon.name": "Honey Lemon",
  "recipe.honey_lemon.desc": "Lemon and honey. Slower, but worth much more.",
  "recipe.mint_sparkle.name": "Mint Sparkle",
  "recipe.mint_sparkle.desc": "Lemon, mint and ice. Quick to make, and brings premium orders.",
  "recipe.berry_fizz.name": "Berry Lemon Fizz",
  "recipe.berry_fizz.desc": "Lemon, berry syrup and soda. Lets combos climb higher.",
  "recipe.peachy_tea.name": "Peachy Lemon Tea",
  "recipe.peachy_tea.desc": "Lemon, peach and tea. Keeps the stand earning while you're away.",
  "recipe.citrus_float.name": "Citrus Float",
  "recipe.citrus_float.desc": "Lemon, cream and ice. Golden lemons appear more often.",
  "recipe.sunbeam_soda.name": "Sunbeam Soda",
  "recipe.sunbeam_soda.desc": "Lemon, golden syrup and soda. A drink for early risers.",
  "recipe.moon_cooler.name": "Moon Lemon Cooler",
  "recipe.moon_cooler.desc": "Lemon, night mint and star sugar. The lane's finest.",

  // Customers
  "customer.mochi_cat.name": "Mochi Cat",
  "customer.mochi_cat.desc": "Patient and sweet. Loves Classic Lemonade.",
  "customer.bun_rabbit.name": "Bun Rabbit",
  "customer.bun_rabbit.desc": "Always in a hurry, but tips well when served fast.",
  "customer.duckling.name": "Duckling",
  "customer.duckling.desc": "Waddles by for Honey Lemon.",
  "customer.squirrel.name": "Squirrel",
  "customer.squirrel.desc": "Collects every sticker. Adores Berry Fizz.",
  "customer.otter.name": "Otter",
  "customer.otter.desc": "Loves a good streak of quick service.",
  "customer.fox.name": "Fox",
  "customer.fox.desc": "Fancy tastes and deep pockets.",
  "customer.turtle.name": "Turtle",
  "customer.turtle.desc": "Slow and steady. Orders three drinks at once.",
  "customer.golden_sun.name": "Golden Sun",
  "customer.golden_sun.desc": "A rare, radiant visitor who pays in sunshine.",

  // Helpers
  "helper.pip.name": "Pip",
  "helper.pip.desc": "Picks ripe lemons for you.",
  "helper.roo.name": "Roo",
  "helper.roo.desc": "Carries drinks to waiting customers.",
  "helper.basil.name": "Basil",
  "helper.basil.desc": "Tinkers with the press so it runs faster.",
  "helper.peony.name": "Peony",
  "helper.peony.desc": "Tends the flowers so customers stay cheerful.",
  "helper.mochi.name": "Mochi",
  "helper.mochi.desc": "Charms the queue into tipping more.",
  "helper.coco.name": "Coco",
  "helper.coco.desc": "Every collection star earns a little more.",
  "helper.nori.name": "Nori",
  "helper.nori.desc": "Draws in premium orders.",
  "helper.sunny.name": "Sunny",
  "helper.sunny.desc": "Brings more Sunny Tokens at each Sunrise.",

  // Regions
  "region.tiny_yard.name": "Tiny Yard",
  "region.tiny_yard.desc": "One tree, one stand, one big dream.",
  "region.sunny_lane.name": "Sunny Lane",
  "region.sunny_lane.desc": "A second tree, a longer queue, and new neighbors.",
  "region.picnic_corner.name": "Picnic Corner",
  "region.picnic_corner.desc": "Picnic tables, new recipes, and new helpers.",
  "region.market_row.name": "Market Row",
  "region.market_row.desc": "Busy stalls, fancy customers, and delivery carts.",
  "region.orchard_hill.name": "Orchard Hill",
  "region.orchard_hill.desc": "Two more trees, and golden lemons turn up more often.",
  "region.riverside.name": "Riverside",
  "region.riverside.desc": "Boat deliveries that keep earning while you're away.",
  "region.sunset_plaza.name": "Sunset Plaza",
  "region.sunset_plaza.desc": "Festival lights and rare recipes. Opens after your first Sunrise.",
  "region.moonlit_market.name": "Moonlit Market",
  "region.moonlit_market.desc": "Night customers under the lanterns. Opens after two Sunrises.",

  // Perks
  "perk.warm_soil.name": "Warm Soil",
  "perk.warm_soil.desc": "Lemons grow 15% faster per level.",
  "perk.sunny_smiles.name": "Sunny Smiles",
  "perk.sunny_smiles.desc": "Customers arrive 10% more often per level.",
  "perk.bright_ideas.name": "Bright Ideas",
  "perk.bright_ideas.desc": "Upgrades cost 4% less per level.",
  "perk.golden_hour.name": "Golden Hour",
  "perk.golden_hour.desc": "Golden lemons are 1% more likely per level.",
  "perk.open_windows.name": "Open Windows",
  "perk.open_windows.desc": "Earn 5% more while away per level.",
  "perk.kind_neighbors.name": "Kind Neighbors",
  "perk.kind_neighbors.desc": "Helpers work 10% faster per level.",
  "perk.fresh_sign.name": "Fresh Sign",
  "perk.fresh_sign.desc": "Premium orders are 2% more likely per level.",
  "perk.longer_days.name": "Longer Days",
  "perk.longer_days.desc": "Away earnings last 1 hour longer per level.",
  "perk.festival_spirit.name": "Festival Spirit",
  "perk.festival_spirit.desc": "Goal and daily basket rewards are 15% bigger per level.",
  "perk.evergreen_lane.name": "Evergreen Lane",
  "perk.evergreen_lane.desc": "Hedges line the lane forever. +25% income.",

  // Cosmetics
  "cosmetic.awning_lemon.name": "Lemon Stripes",
  "cosmetic.awning_lemon.desc": "The original awning.",
  "cosmetic.awning_mint.name": "Mint Stripes",
  "cosmetic.awning_mint.desc": "Fresh as a garden morning.",
  "cosmetic.awning_berry.name": "Berry Stripes",
  "cosmetic.awning_berry.desc": "Sweet and bold.",
  "cosmetic.awning_sky.name": "Sky Stripes",
  "cosmetic.awning_sky.desc": "Calm blue for easy days.",
  "cosmetic.awning_peach.name": "Peach Stripes",
  "cosmetic.awning_peach.desc": "Warm like late summer.",
  "cosmetic.awning_moon.name": "Moon Stripes",
  "cosmetic.awning_moon.desc": "For stands that stay open till the stars come out.",

  // Quests
  "quest.harvest": "Pick {n} ripe lemons",
  "quest.serve": "Serve {n} customers",
  "quest.earn": "Earn {n} coins",
  "quest.buyUpgrade": "Buy {n} upgrade(s)",
  "quest.upgradeLevel": "Raise {ref} to level {n}",
  "quest.hire": "Hire {ref}",
  "quest.region": "Open {ref}",
  "quest.recipe": "Discover {ref}",
  "quest.combo": "Reach a {n}× serving combo",
  "quest.golden": "Pick a golden lemon",
  "quest.sunrise": "Celebrate your first Sunrise",

  // Tutorial hints (shown alongside the first goals)
  "hint.q_first_pick": "Tap the lemon tree when lemons turn bright yellow.",
  "hint.q_first_serve": "The press turns lemons into drinks. Tap a waiting customer to serve them.",
  "hint.q_first_upgrade": "Open Upgrades and pick anything you like. Each one changes the stand.",
  "hint.q_hire_pip": "Helpers work on their own. Pip picks lemons for you.",
  "hint.q_sunny_lane": "Open the Lane tab to expand down the street.",
  "hint.q_hire_roo": "Roo serves customers so the stand runs while you relax.",
  "hint.q_honey": "Recipes trade speed for value. Try Honey Lemon.",
  "hint.q_combo_5": "Serve customers back to back to build a combo.",
  "hint.q_golden": "Golden lemons sparkle. Pick them for a big bonus.",


  // Stat labels (upgrade previews)
  "stat.growthSpeed": "Growth speed",
  "stat.fruitSlots": "Fruit per tree",
  "stat.goldenChance": "Golden lemon chance",
  "stat.basketCap": "Basket space",
  "stat.counterCap": "Counter space",
  "stat.queueSize": "Queue spots",
  "stat.pressSpeed": "Press speed",
  "stat.drinkValue": "Drink value",
  "stat.premiumChance": "Premium orders",
  "stat.premiumBonus": "Premium pay bonus",
  "stat.arrivalRate": "Customers per minute",
  "stat.comboWindow": "Combo time",
  "stat.tipChance": "Tip chance",
  "stat.deliveryRate": "Cart deliveries per minute",
  "stat.offlineEfficiency": "Away earnings",
  "stat.offlineCapHours": "Away time limit",
  "stat.helperSlots": "Helper seats",
  "stat.helperSpeed": "Helper speed",
  "stat.patience": "Customer patience",
  "stat.favoriteBonus": "Favorite drink bonus",
  "stat.recipeDiscount": "Recipe discount",
  "stat.tokenGain": "Sunny Token gain",
  "stat.incomeMult": "Income",
  "stat.upgradeCostScale": "Upgrade prices",
  "stat.rewardMult": "Goal rewards",
  "stat.treeCount": "Lemon trees",
  "stat.starBonus": "Income per collection star",
  "stat.pickEvery": "Picks a lemon every",
  "stat.serveEvery": "Serves a customer every",

  // UI
  "ui.coins": "Coins",
  "ui.perSec": "/s",
  "ui.lemons": "Lemons",
  "ui.drinks": "Drinks",
  "ui.tokens": "Sunny Tokens",
  "ui.stars": "Collection Stars",
  "ui.tab.upgrades": "Upgrades",
  "ui.tab.helpers": "Helpers",
  "ui.tab.recipes": "Recipes",
  "ui.tab.lane": "Lane",
  "ui.tab.sunrise": "Sunrise",
  "ui.tab.goals": "Goals",
  "ui.tab.style": "Style",
  "ui.level": "Lv {n}",
  "ui.max": "Maxed",
  "ui.buy": "Buy",
  "ui.hire": "Hire",
  "ui.open": "Open",
  "ui.discover": "Discover",
  "ui.use": "Use",
  "ui.inUse": "In use",
  "ui.equip": "Wear",
  "ui.equipped": "Wearing",
  "ui.claim": "Claim",
  "ui.close": "Close",
  "ui.cost": "{n} coins",
  "ui.need": "Need {n} more",
  "ui.lockedRegion": "Opens with {ref}",
  "ui.lockedSunrise": "After {n} Sunrise(s)",
  "ui.lockedStars": "{n} stars needed",
  "ui.slotsFull": "Helper Bench is full ({n} seats)",
  "ui.helperSlots": "Helper seats: {a} / {b}",
  "ui.next": "Next: {s}",
  "ui.recipeStats": "{l} lemon(s) · {t}s · {v} coins",
  "ui.goal": "Goal",
  "ui.goalDone": "Done!",
  "ui.daily": "Daily Basket",
  "ui.dailyDesc": "A small gift from the neighbors, once a day.",
  "ui.dailyClaimed": "Come back tomorrow for another basket.",
  "ui.collection": "Collection",
  "ui.stickers": "Customer Stickers",
  "ui.recipeCards": "Recipe Cards",
  "ui.laneSpots": "Lane Spots",
  "ui.awnings": "Awnings",
  "ui.sunriseTitle": "Sunrise",
  "ui.sunriseDesc": "Close this chapter and start a fresh morning. Coins, upgrades, helpers and lane spots reset. Sunny Tokens, perks, stickers, discovered recipes and awnings stay forever, and each recipe is ready again as soon as its lane spot reopens.",
  "ui.sunriseNotYet": "Earn {n} coins this chapter to watch the sun rise.",
  "ui.sunriseReady": "Sunrise now for {n} Sunny Tokens",
  "ui.sunriseConfirm": "Start a new morning? You'll get {n} Sunny Tokens.",
  "ui.sunriseGo": "Sunrise!",
  "ui.cancel": "Not yet",
  "ui.perks": "Sunny Perks",
  "ui.perkCost": "{n} token(s)",
  "ui.settings": "Settings",
  "ui.music": "Music",
  "ui.sfx": "Sound effects",
  "ui.reducedMotion": "Reduced motion",
  "ui.on": "On",
  "ui.off": "Off",
  "ui.welcomeBack": "Welcome back!",
  "ui.awayFor": "You were away for {t}.",
  "ui.awayEarned": "Your stand earned:",
  "ui.awayNothing": "Hire Pip and Roo so the stand keeps working while you're away.",
  "ui.collect": "Collect",
  "ui.collectDouble": "Watch an ad: ×2",
  "ui.adBadge": "AD",
  "ui.burst": "Sunny Rush",
  "ui.burstDesc": "Watch an ad: ×2 income for 90s",
  "ui.burstActive": "Sunny Rush ×2 · {t}s",
  "ui.adFailed": "No ad right now, so no reward this time. Your game is unaffected.",
  "ui.saveQuarantine": "Your save came from a newer version of the game. It's kept safe and untouched.",
  "ui.saveRecovered": "Your save had a problem, so we restored the backup.",
  "ui.saveFailed": "Couldn't save just now. We'll try again shortly.",
  "ui.guest": "Playing as guest",
  "ui.player": "Hi, {n}!",
  "ui.signIn": "Sign in to keep progress on every device",
  "ui.stats": "Chapter {n}",
  "ui.reset": "Erase save",
  "ui.resetConfirm": "Erase ALL progress, including Sunny Tokens and collections? This can't be undone.",
  "ui.resetYes": "Erase everything",
  "ui.toast.newCustomer": "New sticker: {ref}!",
  "ui.toast.golden": "Golden lemon! +{n}",
  "ui.toast.region": "{ref} is open!",
  "ui.toast.recipe": "New recipe: {ref}",
  "ui.toast.cosmetic": "New awning unlocked: {ref}",
  "ui.toast.quest": "Goal complete! Claim your reward.",
  "ui.toast.daily": "Daily basket: +{n}",
  "ui.combo": "Combo ×{n}",
  "ui.premium": "Premium",
  "ui.keys": "Keys: Space = pick · S = squeeze · E = serve · 1–7 = tabs · Esc = close",
  "ui.loading": "Warming up the lane…",
};

let current = EN;

export function t(key: string, params?: Record<string, string | number>): string {
  let s = current[key];
  if (s === undefined) {
    if (import.meta.env?.DEV) console.warn(`[strings] missing key: ${key}`);
    s = key;
  }
  if (params) {
    for (const [k, v] of Object.entries(params)) s = s.split(`{${k}}`).join(String(v));
  }
  return s;
}

export function setStrings(table: Record<string, string>): void {
  current = table;
}

export function nameOf(family: string, id: string): string {
  return t(`${family}.${id}.name`);
}

export function descOf(family: string, id: string): string {
  return t(`${family}.${id}.desc`);
}
